### ISSUE TITLE
allnotesoff not working

### ISSUE THREAD

**Issue by cfry** [cotejp/webmidi#22]
http://cotejp.github.io/webmidi/latest/classes/Output.html
and its crucial content says:
sendChannelMode (command, value, [channel=all], [options={}])
Output chainable

Defined in src/webmidi.js:3793

Sends a MIDI channel mode message to the specified channel(s).

The channel mode message to send can be specified numerically or by using one of the following common names:

allsoundoff (#120)
resetallcontrollers (#121)
localcontrol (#122)
allnotesoff (#123)
omnimodeoff (#124)
omnimodeon (#125)
monomodeon (#126)
polymodeon (#127)

First attempt:
WebMidi.outputs[0].sendChannelMode("allnotesoff")
yields error: RangeError: Value must be integers between 0 and 127.
Hmm, why does allnotesoff need a value and what would iit be?
Can't it default?

In any case, attempt 2:
WebMidi.outputs[0].sendChannelMode("allnotesoff", 0)
doesn't error but doesn't shut off ongoing notes either.
I've tried the variation of using
WebMidi.outputs[0].sendChannelMode("allsoundoff", 0)
as well as using the command numbers instead of strings,
and passing the value of 127.
Didn't turn off ongoing notes playing on GarageBand on Mac.
It's possible that GarageBand doesn't respond to allnotesoff.

**Comment by cotejp** [comment]
Per the [MIDI spec](https://www.midi.org/specifications/item/table-1-summary-of-midi-message), the `allnotesoff` message does require a value of 0. However, since most channel mode messages require a value of 0, I decided to make it the default. 

This means that, starting with [version 2.0.0-rc.8](https://github.com/cotejp/webmidi/releases/tag/2.0.0-rc.8), you can omit the value parameter altogether:

```javascript
WebMidi.outputs[0].sendChannelMode('allnotesoff');
```
Regarding GarageBand, it is very possible that it does not support MIDI channel mode commands. As a matter of fact, it seems you're not the only one with [this issue](https://discussions.apple.com/thread/3822107?start=0&tstart=0).

**Comment by cfry** [comment]
Thanks so much for the speedy reply.
I'm just about to make a release of my development environment.
This is the LAST thing that got in.
Too bad it doesn't work in GarageBand but KNOWING that
is worth a lot. WebMidi.js rocks!
